import express from 'express';
import cors from 'cors';
import path from 'path';
import fs from 'fs';
import { initDb } from './db.js';
import { initGeoIP } from './geoip.js';
import { initScheduler } from './scheduler.js';

// Routers
import authRouter from './routes/auth.js';
import sourcesRouter from './routes/sources.js';
import subscriptionsRouter from './routes/subscriptions.js';
import epgRouter from './routes/epg.js';
import settingsRouter from './routes/settings.js';
import exportRouter from './routes/export.js';
import optimizerRouter from './routes/optimizer.js';
import miguRouter from './routes/migu.js';
import streamsRouter from './routes/streams.js';
import { HLS_ROOT, hlsIndexHandler, initStreamIdleMonitor, touchStreamFromPath } from './streamer.js';
import { scanGuardMiddleware } from './clientScanGuard.js';
import { ensureLogoIndex } from './logoLibrary.js';
import { handleHlsProxyIndex, handleHlsProxySegment } from './hlsProxy.js';
import { handleFlvProxyRoute } from './flvProxy.js';

const app = express();
const PORT = process.env.PORT || 4010;

// Enable CORS for API development
app.use(cors());
app.use(express.json({ limit: '10mb' }));
app.use(express.urlencoded({ extended: true, limit: '10mb' }));

// 1. Initialize DB and Services
console.log('Initializing IPTV Management System backend...');
initDb();

// Async services initialization
async function startServices() {
  await initGeoIP();
  initScheduler();
  initStreamIdleMonitor();
  ensureLogoIndex().catch(err => {
    console.warn('Initial logo index fetch warning:', err.message);
  });
}
startServices().catch(err => {
  console.error('Error starting async background services:', err);
});

// Host local custom logos if any
const logosPath = path.resolve('./data/logos');
if (!fs.existsSync(logosPath)) {
  fs.mkdirSync(logosPath, { recursive: true });
}
app.use('/logos', express.static(logosPath));

// 2. Bind Public Export/Subscription Router directly to root '/'
app.use('/', exportRouter);

// 3. Bind Admin Management API Routers
app.use('/api/auth', authRouter);
app.use('/api/sources', sourcesRouter);
app.use('/api/subscriptions', subscriptionsRouter);
app.use('/api/epg', epgRouter);
app.use('/api/settings', settingsRouter);
app.use('/api/optimizer', optimizerRouter);
app.use('/api/migu', miguRouter);
app.use('/api/streams', streamsRouter);

// HLS stream files generated by ffmpeg with scan guard protection
app.use('/stream/hls', scanGuardMiddleware);
app.get('/stream/hls/:sourceId/index.m3u8', hlsIndexHandler);
app.use('/stream/hls', (req, res, next) => {
  touchStreamFromPath(req.path);
  next();
}, express.static(HLS_ROOT, {
  fallthrough: true,
  setHeaders: (res, filePath) => {
    if (filePath.endsWith('.m3u8')) res.setHeader('Content-Type', 'application/vnd.apple.mpegurl');
    if (filePath.endsWith('.ts')) res.setHeader('Content-Type', 'video/mp2t');
  }
}));

// HLS Full Same-Origin Proxy Mode (no disk write, on-the-fly relative m3u8 rewriting)
app.use('/stream/proxy', scanGuardMiddleware);
app.get('/stream/proxy/:sourceId/index.m3u8', handleHlsProxyIndex);
app.get('/stream/proxy/:sourceId/segment/:segKey', handleHlsProxySegment);

// HTTP-FLV Zero-Transcode Streaming Proxy
app.get('/stream/flv/:sourceId', handleFlvProxyRoute);

// 4. Host static files for frontend build
const publicPath = path.resolve('./public');
if (!fs.existsSync(publicPath)) {
  fs.mkdirSync(publicPath, { recursive: true });
}
app.use(express.static(publicPath));

// 5. Fallback for React Router single page app
app.get('*', (req, res, next) => {
  // Skip if it looks like an API route
  if (req.path.startsWith('/api/') || req.path.startsWith('/stream/') || req.path.startsWith('/m3u') || req.path.startsWith('/txt') || req.path.startsWith('/ipv') || req.path.startsWith('/hls')) {
    return next();
  }
  const indexPath = path.join(publicPath, 'index.html');
  if (fs.existsSync(indexPath)) {
    res.sendFile(indexPath);
  } else {
    res.send('IPTV Admin Backend is running. Frontend static index.html not found under ./public');
  }
});

// Start listening
app.listen(PORT, '0.0.0.0', () => {
  console.log(`IPTV Management backend is listening on http://0.0.0.0:${PORT}`);
});
